export const RankingsData = [
    { title: "Jaydon Ekstrom Bothman", avatar: 'Avatar1' },
    { title: "Ruben Carder", avatar: 'Avatar1' },
    { title: "Alfredo Septimus", avatar: 'Avatar1' },
    { title: "Davis Franci", avatar: 'Avatar1' },
    { title: "Livia Rosser", avatar: 'Avatar1' },
    { title: "Kianna Donin", avatar: 'Avatar1' },
    { title: "Phillip Lipshutz", avatar: 'Avatar1' },
    { title: "Maria Rosser", avatar: 'Avatar1' },
    { title: "Kiana Stanton", avatar: 'Avatar1' },
    { title: "Angel Lubin", avatar: 'Avatar1' },
    { title: "Allison Torff", avatar: 'Avatar1' },
    { title: "Davis Workman", avatar: 'Avatar1' },
    { title: "Lindsey Lipshutz", avatar: 'Avatar1' },
    { title: "Randy Carder", avatar: 'Avatar1' },
    { title: "Lydia Culhane", avatar: 'Avatar1' },
    { title: "Rayna Bator", avatar: 'Avatar1' },
    { title: "Jocelyn Westervelt", avatar: 'Avatar1' },
    { title: "Marilyn Torff", avatar: 'Avatar1' },
    { title: "Skylar Levin", avatar: 'Avatar1' },
    { title: "Terry Dorwart", avatar: 'Avatar1' },
]